spring.application.name=fit-check

# Where uploaded files are stored (a folder in your project root)
file.upload-dir=uploads

# Allow reasonably large image uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/